### PR TITLE
Remove blueprints

### LINKED ISSUE #120: Disable JSHint "expr" rule
The `ember-cli-mocha` blueprint should disable the `expr` JSHint rule in `tests/.jshintrc` if the file exists. 

see https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/33 and related PRs

### LINKED ISSUE #121: Inconsistent test names
Examples:

- `Integration: PrettyButtonComponent` (component integration test)
- `PrettyButtonComponent` (component unit test)
- `UsersController` (controller unit test)
- `Unit | Model | user` (model unit test)

the last one seems correct and is using the new test name style, but the other ones are obviously incorrect.

This was tested on a fresh Ember CLI 2.7.0 app.

### PR DESCRIPTION
**Pull request by Turbo87**
These blueprints have been moved into [ember.js](https://github.com/emberjs/ember.js/tree/master/blueprints), [ember-data](https://github.com/emberjs/data/tree/master/blueprints) and [ember-cli-legacy-blueprints](https://github.com/ember-cli/ember-cli-legacy-blueprints/tree/master/blueprints).

Merging this will require a major version bump (actually only a minor since we're still sub-1.0), but due to the JSHint removal that is necessary anyway. 

This PR resolves #120, resolves #121 and obsoletes #81 and #118.

/cc @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
@rwjblue any comments?

**Comment by Turbo87** [comment]
now that this is an `ember-cli` project: @ember-cli/core any comments?

**Comment by chadhietala** [comment]
LGTM

**Comment by stefanpenner** [comment]
👍

**Comment by nathanhammond** [comment]
YESSS. 😛

**Pull request merged**
