### PR TITLE
Split "chai" code into "ember-cli-chai" addon

### LINKED ISSUE #132: Split "chai" code into ember-cli-chai
Mocha is often used in combination with Chai, but it is not required and some people might prefer other assertion libraries. Should we split this library into `ember-cli-mocha` and `ember-cli-chai`?

/cc @dgeb @rwjblue @stefanpenner @alexlafroscia

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-cli-chai

Resolves #132 

/cc @rwjblue @alexlafroscia

### CODE REVIEW

**Comment by Turbo87** [comment]
thanks @rwjblue

**Comment by Turbo87** [comment]
@rwjblue eventually I'd like to move the `ember-cli-chai` dependency into the default blueprint so that users can decide for themselves which version they want to use (chai 4.0 will be released soon with a few breaking changes)

**Comment by rwjblue** [comment]
Right, makes sense

**Comment by alexlafroscia** [comment]
Looks good to me, too!

**Pull request merged**
