### PR TITLE
use @elbeezy & @SaladFork style and reporter as default

### PR DESCRIPTION
**Pull request by ballPointPenguin**
This is currently blocked by a bug in ember-cli which has been fixed but not released
https://github.com/ember-cli/ember-cli/pull/4659

### CODE REVIEW

**Comment by ballPointPenguin** [comment]
alternatively, this could be its own stand-alone add-on.

**Comment by shaunc** [comment]
I was eager to try this out, so I installed ember-cli from master, but got error:

ReferenceError: event is not defined (Error in blueprint template: /Volumes/Macintosh_HD/Users/shauncutts/src/ember-grid/node_modules/ember-cli-mocha/blueprints/ember-cli-mocha/files/tests/helpers/reporter.js)

Is this perhaps because I didn't clear caches etc before new ember-cli, or is it something else.

**Comment by ballPointPenguin** [comment]
@shaunc That is a known issue that will be fixed in the next release of ember-cli.
https://github.com/ember-cli/ember-cli/pull/4659
A workaround is to build ember-cli from master.

**Comment by Dhaulagiri** [comment]
@ballPointPenguin any interest in trying to get this landed?

**Comment by ballPointPenguin** [comment]
@Dhaulagiri yes. Thanks for the nudge :smile: 
I'll look into it.

**Comment by ballPointPenguin** [comment]
I would like to test this in some new example projects at different versions before it gets merged.

**Comment by ballPointPenguin** [comment]
screenshot from 2015-12-15 20-42-51

**Comment by ballPointPenguin** [comment]
I'm pretty happy with where this is at. Do we want to include this reporter and its css as the default?
If so, this PR is ready to go.

Thoughts?
@ef4 @SaladFork @elbeezy

**Comment by ballPointPenguin** [comment]
sample repo: https://github.com/ballPointPenguin/mocha-latte

**Comment by rwjblue** [comment]
I am generally fine with making this the default, and as such I would prefer to keep it out of the blueprint (we would just put these files in `test-support/` in the addon, and they are then merged with `tests/` in the app).  

Basically, I see everything that we blueprint into the app as code that the app author must maintain, and this is not code they maintain (it is something that we would maintain here in ember-cli-mocha).

**Comment by Dhaulagiri** [comment]
Out of curiosity, where do the coverage stats come from @ballPointPenguin?

Another thing is that when I pulled this manually into our project I adjusted the container to work more like qunit's so that it was always visible but could be hidden via checkbox toggle.  Having to float off to the side did not seem very discoverable.

**Comment by ballPointPenguin** [comment]
thanks for the clarification @rwjblue I will modify the PR.

**Comment by ballPointPenguin** [comment]
@Dhaulagiri coverage comes from ember-cli-blanket
Having a show/hide toggle for the container would be nice. Perhaps you can add that and/or share the code here?

**Comment by Dhaulagiri** [comment]
Sure thing.  I wil try to find a few minutes and make a PR to your branch or something.  

If one does not have ember-cli-blanket installed does the coverage piece still appear?

**Comment by Dhaulagiri** [comment]
@ballPointPenguin if you add me as a collaborator to your fork I can open a PR against it that shows most of the code needed

**Comment by ballPointPenguin** [comment]
@Dhaulagiri added you.
Without ember-cli-blanket, the checkbox still appears, but has no effect.
When I get time (today), I'm going to refactor my PR per rwjblue's suggestion above, but feel free to commit to it before or after that happens.

**Comment by SaladFork** [comment]
Hi all, I greatly appreciate the enthusiasm (especially @ballPointPenguin, thanks!). I definitely agree that there is potential for improvement in the Mocha HTML reporter.

That said, I'm not entirely convinced that at its current state (the code I wrote that is; @ballPointPenguin's iterations have been good) it is ready for being the default for all `ember-cli-mocha` users, especially as the code was mostly a weekend spike inspired by Edward Faulkner's [better-mocha-html-reporter](https://github.com/ef4/better-mocha-html-reporter). Especially when it comes to dealing with a test environment, I feel we should be extra careful to not introduce any risk. The last thing we want is developers having to dig through our reporter code to try and figure out a false positive/negative.

If we're going to merge into `ember-cli-mocha` and make it the default for Ember Mocha users I'd really like to make sure we have a reporter that is tested. I'd also like at the very least to clean up a few of the messier bits of the code, including:
 * The grouping of linting results, as it's currently sort of brute forced, done after-the-fact, and not generic for use with other-than-JSHint linting such as JSCS (though this has been somewhat improved in the latest gist revision)
 * Better visibility as to which test is currently being run (I believe right now it just shows nothing at all)
 * The need for users to find and manually insert the `testGenerator` function
 * The way-too-aggressive technique used for overriding CSS styles
 * Add a proper mechanism for registering new options that are reflected and managed in the URL. Not only is my current solution brittle, this is also a clear gap between what QUnit offers and what Mocha does. I feel we can bridge this. This can be used for toggling hiding passed, toggling coverage, hiding the container on the side, showing notifications, etc.

All of this is leading me to want to create this as a separate addon for now (either on top of `ember-cli-mocha` or instead of), and once it has matured a bit look at if merging the two makes sense. I've created [ember-cli-iced-mocha](https://github.com/SaladFork/ember-cli-iced-mocha) to explore this a bit and put in some initial code I'd like to iterate on and build up.

Longer term, I'd also like to separate the data code from the view code from the event handling and logic. Rather than write our own separate layers I think we might be able to get the reporter to be an Ember application running on the `tests/index.html` page, separate from the app-under-test, and have it driven by the mocha runner events updating state. I suspect it might involve some broccoli fun but wouldn't be impossible.

**Comment by ballPointPenguin** [comment]
@SaladFork I appreciate your vision and high standards. I agree with everything in your comment. I would especially like to see some work around the testGenerator function (I'm currently hacking it in my ember-cli-build.js).
I think feature parity with the ember-qunit reporter is a good goal, but it would be cool to go further than that, as you outlined. I will try to contribute however I can.

**Comment by mmelvin0** [comment]
(Sorry for double posting, meant to put this here originally...)

I combined the work of @ef4, @SaladFork, and @lolmaus (and perhaps others) into a proper Ember-CLI addon as I found the default Mocha test runner to be a bit lacking. Feedback is welcomed.

https://github.com/mmelvin0/ember-cli-mocha-reporter

**Comment by Turbo87** [comment]
as @mmelvin0 demonstrated custom reporters can be added on top of this plugin so I'm going to close this issue for now

**Pull request closed without merging**
